Use '--' instead of '-' when emitting sql with `cargo pgx schema`
zombodb/pgx pull request #437
Opened 2022-02-14 15:55 UTC by JamesGuthrie

2022-02-14 16:03 UTC, JamesGuthrie commented
Relates to #438

2022-02-14 17:29 UTC, Hoverbear requested changes
This results in some problems with the user workflow when `cargo pgx schema` is called before `cargo pgx package`:

```bash
ana@autonoma:~/git/zombodb/pgx/pgx-examples/arrays$ cargo pgx schema
    Building SQL generator with features ``
"cargo" "build" "--bin" "sql-generator"
   Compiling pgx-pg-sys v0.3.1 (/home/ana/git/zombodb/pgx/pgx-pg-sys)
   Compiling pgx v0.3.1 (/home/ana/git/zombodb/pgx/pgx)
   Compiling arrays v0.1.0 (/home/ana/git/zombodb/pgx/pgx-examples/arrays)
    Finished dev [unoptimized + debuginfo] target(s) in 38.07s
 Discovering SQL entities
  Discovered 14 SQL entities: 0 schemas (0 unique), 13 functions, 1 types, 0 enums, 0 sqls, 0 ords, 0 hashes, 0 aggregates
running SQL generator
"/home/ana/git/zombodb/pgx/pgx-examples/arrays/target/debug/sql-generator" "--sql" "sql/arrays--0.1.0.sql"


ana@autonoma:~/git/zombodb/pgx/pgx-examples/arrays$ cargo pgx package
building extension with features ``
"cargo" "build" "--release"
    Finished release [optimized] target(s) in 0.07s

installing extension
     Copying control file to `target/release/arrays-pg13/usr/share/postgresql/13/extension/arrays.control`
     Copying shared library to `target/release/arrays-pg13/usr/lib/postgresql/13/lib/arrays.so`
 Discovering SQL entities
  Discovered 14 SQL entities: 0 schemas (0 unique), 13 functions, 1 types, 0 enums, 0 sqls, 0 ords, 0 hashes, 0 aggregates
running SQL generator
"/home/ana/git/zombodb/pgx/pgx-examples/arrays/target/release/sql-generator" "--sql" "/home/ana/git/zombodb/pgx/pgx-examples/arrays/target/release/arrays-pg13/usr/share/postgresql/13/extension/arrays--0.1.0.sql"
     Copying extension schema file to `target/release/arrays-pg13/usr/share/postgresql/13/extension/arrays--0.1.0.sql`
     Copying extension schema upgrade file to `target/release/arrays-pg13/usr/share/postgresql/13/extension/arrays--0.1.0.sql`
    Finished installing arrays
```

I'm fairly sure

```bash
     Copying extension schema upgrade file to `target/release/arrays-pg13/usr/share/postgresql/13/extension/arrays--0.1.0.sql`
```

This means it's copying the old `cargo pgx schema` run output over top the 'current' output?

Here's the `develop` branch output:

```bash
ana@autonoma:~/git/zombodb/pgx/pgx-examples/arrays$ cargo pgx schema
    Building SQL generator with features ``
"cargo" "build" "--bin" "sql-generator"
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
 Discovering SQL entities
  Discovered 14 SQL entities: 0 schemas (0 unique), 13 functions, 1 types, 0 enums, 0 sqls, 0 ords, 0 hashes, 0 aggregates
running SQL generator
"/home/ana/git/zombodb/pgx/pgx-examples/arrays/target/debug/sql-generator" "--sql" "sql/arrays-0.1.0.sql"


ana@autonoma:~/git/zombodb/pgx/pgx-examples/arrays$ cargo pgx package
building extension with features ``
"cargo" "build" "--release"
    Finished release [optimized] target(s) in 0.07s

installing extension
     Copying control file to `target/release/arrays-pg13/usr/share/postgresql/13/extension/arrays.control`
     Copying shared library to `target/release/arrays-pg13/usr/lib/postgresql/13/lib/arrays.so`
 Discovering SQL entities
  Discovered 14 SQL entities: 0 schemas (0 unique), 13 functions, 1 types, 0 enums, 0 sqls, 0 ords, 0 hashes, 0 aggregates
running SQL generator
"/home/ana/git/zombodb/pgx/pgx-examples/arrays/target/release/sql-generator" "--sql" "/home/ana/git/zombodb/pgx/pgx-examples/arrays/target/release/arrays-pg13/usr/share/postgresql/13/extension/arrays--0.1.0.sql"
     Copying extension schema file to `target/release/arrays-pg13/usr/share/postgresql/13/extension/arrays--0.1.0.sql`
    Finished installing arrays
```

Looking at this, it's not quite right either. The `sql-generator` outputs to the destination directly, and we don't need to do this step:

```rust
     Copying extension schema file to `target/release/arrays-pg13/usr/share/postgresql/13/extension/arrays--0.1.0.sql`
```

I think we need to ignore this generated file in the `package` step.

2022-02-15 06:31 UTC, JamesGuthrie commented
> This means it's copying the old cargo pgx schema run output over top the 'current' output?

That's correct. That's also a behaviour which I find a bit odd. In this specific constellation, it seems obvious that `cargo pgx package` should ignore the file which is already present, but if the user provides a custom, hand-written sql file, should `cargo pgx package` overwrite that with its own output?

2022-02-15 11:20 UTC, JamesGuthrie commented
As a follow-on to my previous comment: this also happens when using `cargo pgx schema` followed by `cargo pgx test`, which is a little more annoying, because it doesn't install the `tests` schema, and suddenly all tests fail.

2022-03-02 21:56 UTC, Hoverbear commented
Hey @JamesGuthrie , @eeeebbbbrrrr and I have been discussing and we actually think we want to solve this differently.

`cargo pgx schema` used to process the Rust source files and write out this new SQL file into the `sql/` folder. This was necessary for how `pgx` worked before.... however we don't need to do any of that anymore! Some extensions don't even have a `sql/` folder, even!

So we're thinking it'd be better if `cargo pgx schema` wrote the produced SQL to `stdout` instead. This way we're not producing these SQL files at all.

2022-03-02 22:22 UTC, eeeebbbbrrrr commented
I'm excited for this change!

2022-03-04 20:07 UTC, Hoverbear commented
Thanks for this @JamesGuthrie :)

2022-03-04 20:07 UTC, closed without merging